services:


  postgres:
    build:
      context: postgres
      dockerfile: postgres.Dockerfile
    container_name: bvito_db
    env_file:
      - postgres/.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 60s
      timeout: 3s
      retries: 3
      start_period: 7s
      start_interval: 1s


volumes:
  pgdata: