services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - bvito_logs:/var/log/bvito
      - bvito_static:/static
    depends_on:
      - postgres

  postgres:
    image: postgres:17.4-alpine
    container_name: bvito_db
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5


volumes:
  pg_data:
  bvito_logs:
  bvito_static: