spring:
  application:
    name: Bvito
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    org.springframework: ERROR

server:
  port: 8000
  error:
    include-stacktrace: never
  tomcat:
    connection-timeout: 1s
    keep-alive-timeout: 30s
    max-keep-alive-requests: 100