spring:
  application:
    name: Bvito
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    org.springframework: ERROR

server:
  port: 8000
  error:
    include-stacktrace: never
  tomcat:
    connection-timeout: 1s
    keep-alive-timeout: 30s
    max-keep-alive-requests: 100

photos:
  upload-dir: "classpath:/static/ad_photos/"